import type { Metadata } from "next";
import "../globals.css";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "react-hot-toast"; // ✅ import

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "MEILI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.className} ${geistMono.variable} antialiased`}>
        <Toaster
            position="top-center"
            containerStyle={{
                top: '40%',
            }}
            toastOptions={{
                style: {
                    background: '#1e293b', // Dark background එකක්
                    color: '#fff',
                    borderRadius: '15px',
                    padding: '12px 24px',
                    fontSize: '14px',
                    fontWeight: '600'
                }
            }}
            reverseOrder={false}
        />
        {children}
        </body>
        </html>
    );
}