import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "M E I L I",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        {/* GeistSans.className eka main font eka widiyata body ekata danna.
            Mono eka variable ekak widiyata thiyanna thawa thanaka use karanna ona nam. */}
        <body className={`${geistSans.className} ${geistMono.variable} antialiased bg-gray-50`}>
        <Navbar />
        {children}
        <Footer />
        </body>
        </html>
    );
}